autocommit on change

diff --git a/mingw-w64-gcc-git/PKGBUILD b/mingw-w64-gcc-git/PKGBUILD
--- a/mingw-w64-gcc-git/PKGBUILD
+++ b/mingw-w64-gcc-git/PKGBUILD
@@ -39,7 +39,7 @@ makedepends=("${MINGW_PACKAGE_PREFIX}-${_realname}"
              "${MINGW_PACKAGE_PREFIX}-windows-default-manifest"
              "${MINGW_PACKAGE_PREFIX}-winpthreads"
              "${MINGW_PACKAGE_PREFIX}-zlib")
-#checkdepends=('dejagnu')
+checkdepends=(dejagnu inetutils)
 optdepends=()
 options=('staticlibs' '!emptydirs' '!strip' 'debug')
 
@@ -202,7 +202,11 @@ build() {
     --disable-symvers \
     --with-libiconv \
     --with-system-zlib \
+    --enable-gnu-unique-object \
+    --enable-linker-build-id \
     --disable-libstdcxx-verbose \
+    --enable-install-libiberty \
+    --enable-gnu-indirect-function \
     --with-diagnostics-color=always \
     --with-{gmp,mpfr,mpc,isl}=${MINGW_PREFIX} \
     --with-isl \
@@ -231,6 +235,17 @@ build() {
   if [ "$_enable_ada" == "yes" ]; then
     mv ${srcdir}${MINGW_PREFIX}/lib/gcc/${MINGW_CHOST}/${_realpkgver}/adalib/*.dll ${srcdir}${MINGW_PREFIX}/bin/
   fi
+}
+
+check() {
+  cd ${srcdir}/${_sourcedir}
+
+  # disable libphobos test to avoid segfaults and other unfunny ways to waste my time  
+  sed -i '/maybe-check-target-libphobos \\/d' Makefile 
+
+  # do not abort on error as some are "expected"
+  make -k check || true
+  "$srcdir/${_sourcedir}/contrib/test_summary"
 }
 
 package_mingw-w64-gcc-libs-git() {
