autocommit on change

diff --git a/mingw-w64-openssl/PKGBUILDX b/mingw-w64-openssl/PKGBUILDX
--- a/mingw-w64-openssl/PKGBUILDX
+++ b/mingw-w64-openssl/PKGBUILDX
@@ -3,10 +3,10 @@
 _realname=openssl
 pkgbase=mingw-w64-${_realname}
 pkgname=("${MINGW_PACKAGE_PREFIX}-${_realname}")
-_ver=1.0.2t
+_ver=1.0.2s
 # use a pacman compatible version scheme
 pkgver=${_ver/[a-z]/.${_ver//[0-9.]/}}
-pkgrel=61
+pkgrel=92
 arch=('any')
 pkgdesc="The Open Source toolkit for Secure Sockets Layer and Transport Layer Security (mingw-w64)"
 depends=("${MINGW_PACKAGE_PREFIX}-ca-certificates" "${MINGW_PACKAGE_PREFIX}-gcc-libs" "${MINGW_PACKAGE_PREFIX}-zlib")
@@ -14,7 +14,8 @@ makedepends=("${MINGW_PACKAGE_PREFIX}-gcc")
 options=('strip' '!buildflags' 'staticlibs')
 license=('BSD')
 url="https://www.openssl.org"
-source=("${_realname}"::"git+https://github.com/openssl/${_realname}#branch=OpenSSL_1_0_2-stable"
+noextract=(${_realname}-${_ver}.tar.gz)
+source=(https://www.openssl.org/source/${_realname}-${_ver}.tar.gz{,.asc}
         'openssl-1.0.0a-ldflags.patch'
         'openssl-1.0.2a-parallel-build.patch'
         'openssl-1.0.1-x32.patch'
@@ -32,48 +33,44 @@ sha256sums=('50a98e07b1a89eb8f6a99477f262df71c6fa7bef77df4dc83025a2845c827d00'
 validpgpkeys=('8657ABB260F056B1E5190839D9C4D26D0E604491')
 
 prepare() {
-  cd ${srcdir}/${_realname}
+  # Clean up old sources so re-patching doesn't fail.
+  [[ -d ${srcdir}/${_realname}-${_ver} ]] && rm -rf ${srcdir}/${_realname}-${_ver}
+  tar -xzvf ${_realname}-${_ver}.tar.gz -C ${srcdir} || true
+  cd ${srcdir}/${_realname}-${_ver}
 
   patch -p1 -i ${srcdir}/openssl-1.0.0a-ldflags.patch
-  #patch -p1 -i ${srcdir}/000-parallellez.patch
+  patch -p1 -i ${srcdir}/000-parallellez.patch
   patch -p1 -i ${srcdir}/openssl-1.0.1-x32.patch
   patch -p1 -i ${srcdir}/openssl-0.9.6-x509.patch
+#  patch -p1 -i ${srcdir}/openssl-1.0.1i-relocation.patch
 }
 
 build() {
   # No support for out-of-source builds
   mkdir -p ${srcdir}/build-${CARCH}
-  cp -a ${srcdir}/${_realname}/* ${srcdir}/build-${CARCH}
+  cp -a ${srcdir}/${_realname}-${_ver}/* ${srcdir}/build-${CARCH}
 
   # Use mingw cflags instead of hardcoded ones
-  sed -i -e '/^"mingw64"/ s/-DL_ENDIAN -O3/-DL_ENDIAN -march=haswell -pipe -O3/' ${srcdir}/build-${CARCH}/Configure
-  #sed -i -e '/^"mingw64"/ s/-DL_ENDIAN -O3/-DL_ENDIAN -march=haswell -pipe -O3 -fomit-frame-pointer -ffunction-sections -fdata-sections -Wl,--gc-sections/' ${srcdir}/build-${CARCH}/Configure
+  sed -i -e '/^"mingw64"/ s/-DL_ENDIAN -O3/-DL_ENDIAN -march=native -pipe -O3/' ${srcdir}/build-${CARCH}/Configure
+  #sed -i -e '/^"mingw64"/ s/-DL_ENDIAN -O3/-DL_ENDIAN -march=native -pipe -O3s/' ${srcdir}/build-${CARCH}/Configure
   #sed -i -e '/^"mingw"/ s/-fomit-frame-pointer -O3 -march=i486 -Wall/-O2 -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4/' ${srcdir}/build-${CARCH}/Configure
 
-  _mingw=mingw
-  if $(echo ${CARCH} | grep -q x86_64); then
-    _mingw=mingw64
-  fi
+ # _mingw=mingw
+ # if $(echo ${CARCH} | grep -q x86_64); then
+ #   _mingw=mingw64
+ # fi
   cd "${srcdir}/build-${CARCH}"
-  export MSYS2_ARG_CONV_EXCL="--prefix="
+ # export MSYS2_ARG_CONV_EXCL="--prefix="
   ./Configure \
     --prefix=${MINGW_PREFIX} \
     ${_mingw} \
     shared \
+    threads \
     no-zlib \
     no-zlib-dynamic \
-    enable-camellia \
-    enable-unit-test \
-    enable-idea \
-    enable-mdc2 \
-    enable-rfc3779 \
-    enable-ec2m \
-    enable-md2 \
-    enable-rc5 \
-    enable-ec_nistp_64_gcc_128
+    mingw64
 
-    noti make depend -j1
-    noti make -j1
+    noti make depend; noti make
 }
 
 package() {
