autocommit on change

diff --git a/1gcc/PKGBUILD b/1gcc/PKGBUILD
--- a/1gcc/PKGBUILD
+++ b/1gcc/PKGBUILD
@@ -140,16 +140,7 @@ prepare() {
      0030-newlib-ftm.patch \
      0031-define_std-unix.patch \
      0032-fix-ada-malloc-error.patch \
-     gcc-stable-branch.patch \
-     010-documentation.patch \
-     0000-libtool-leave-framework-alone.patch \
-     0002-gcc-plugin-Win-Dont-need-undefined-extern-var-refs-nor-fpic.patch \
-     0003-gcc-plugin-POSIX-include-sys-select-h.patch \
-     0006-libgfortran-missing-include.patch \
-     0008-libgcc-disable-split-stack-nothreads.patch \
-     gdc_thunk_weak_ref.patch \
-     gdc_phobos_path.patch \
-     gdc_artificial_decl.patch
+     gcc-stable-branch.patch
 
   # MINGW Patches
   apply_patch_with_msg 0130-libstdc++-in-out.patch
@@ -164,7 +155,7 @@ prepare() {
   #sed -i 's@\./fixinc\.sh@-c true@' gcc/Makefile.in
   echo ${pkgver} > gcc/BASE-VER
   # hack! - some configure tests for header files using "$CPP $CPPFLAGS"
-  # sed -i "/ac_cpp=/s/\$CPPFLAGS/\$CPPFLAGS -O2/" {libiberty,gcc}/configure
+  sed -i "/ac_cpp=/s/\$CPPFLAGS/\$CPPFLAGS -O2/" {libiberty,gcc}/configure
   
   [[ -d ${srcdir}/build-$(arch) ]] && rm -rf ${srcdir}/build-$(arch)
   mkdir ${srcdir}/build-$(arch)
@@ -194,8 +185,7 @@ build() {
   # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=48565
   CFLAGS=${CFLAGS/-pipe/}
   CXXFLAGS=${CXXFLAGS/-pipe/}
-  LDFLAGS=${LDFLAGS/-pipe/}
-
+  
   # use built-in SSP with Cygwin 2.10
   # FIXME: --disable-libssp should suffice in GCC 8
   export gcc_cv_libc_provides_ssp=yes
@@ -238,6 +228,14 @@ build() {
      noti nice -n 19 make
 }
 
+#check() {
+#  cd ${srcdir}/build-$(arch)
+
+#  # do not abort on error as some are "expected"
+#  make -k check || true
+#  ${srcdir}/gcc-${pkgver}/contrib/test_summary
+#}
+
 package_gcc-libs()
 {
   pkgdesc="Runtime libraries shipped by GCC"
@@ -268,6 +266,10 @@ package_gcc-libs()
 
   # remove static libraries
   #find ${pkgdir} -name *.a -delete
+
+  # Install Runtime Library Exception
+  install -Dm644 ${srcdir}/gcc-${pkgver}/COPYING.RUNTIME \
+    ${pkgdir}/usr/share/licenses/gcc-libs/RUNTIME.LIBRARY.EXCEPTION
 }
 
 package_gcc()
@@ -373,4 +375,8 @@ package_gcc-fortran()
   rm ${pkgdir}/usr/share/info/libquadmath.info
   rm -r ${pkgdir}/usr/lib/gcc/$CHOST/${pkgver}/include
   # rm ${pkgdir}/usr/lib/gcc/$CHOST/${pkgver}/libgfortran.a
+
+  # Install Runtime Library Exception
+  install -Dm644 ${srcdir}/gcc-${pkgver}/COPYING.RUNTIME \
+    ${pkgdir}/usr/share/licenses/gcc-fortran/RUNTIME.LIBRARY.EXCEPTION
 }
