autocommit on change

diff --git a/mingw-w64-rust/PKGBUILD22 b/mingw-w64-rust/PKGBUILD22
--- a/mingw-w64-rust/PKGBUILD22
+++ b/mingw-w64-rust/PKGBUILD22
@@ -20,8 +20,6 @@ makedepends=("bison"
              "${MINGW_PACKAGE_PREFIX}-curl"
              "${MINGW_PACKAGE_PREFIX}-libffi"
              "${MINGW_PACKAGE_PREFIX}-libssh2"
-             "${MINGW_PACKAGE_PREFIX}-lldb"
-             "${MINGW_PACKAGE_PREFIX}-llvm"
              "${MINGW_PACKAGE_PREFIX}-ninja"
              "${MINGW_PACKAGE_PREFIX}-openssl"
              "${MINGW_PACKAGE_PREFIX}-python2"
@@ -63,42 +61,40 @@ build() {
   [[ -d "${srcdir}/${CARCH}" ]] && rm -rf "${srcdir}/${CARCH}"
   mkdir -p "${srcdir}/${CARCH}" && cd "${srcdir}/${CARCH}"
 
- cat >config.toml <<END
-[llvm]
-link-shared = false
-ninja = true
-ccache = ["${MINGW_PREFIX}/bin/ccache"]
+  #We have to do the following because rust doesn't count x86_64-w64-mingw32 as a target triple
+  OSTYPE="$CARCH-pc-windows-gnu"
 
-[build]
-build = ["x86_64-pc-windows-gnu"]
-host = ["x86_64-pc-windows-gnu"]
-target = ["x86_64-pc-windows-gnu"]
-tools = ["cargo", "rls", "clippy", "miri", "rustfmt", "analysis", "src"]
-python = ["${MINGW_PREFIX}/bin/python2"]
-extended = true
-sanitizers = false
-profiler = true
-vendor = true
+  local -a _rust_conf=()
+  if [ "${_bootstrapping}" = "no" ]; then
+    _rust_conf+=("--local-rust-root=$(cygpath -m ${MINGW_PREFIX})")
+  fi
 
-[install]
-prefix = ["${MINGW_PREFIX}"]
-sysconfdir = ["${MINGW_PREFIX}/etc"]
-localstatedir = ["${MINGW_PREFIX}/var/lib"]
+  MSYS2_ARG_CONV_EXCL="--prefix;--sysconfdir;--localstatedir" \
+  ../${_realname}c-${pkgver}-src/configure \
+    --prefix=${MINGW_PREFIX} \
+    --sysconfdir=${MINGW_PREFIX}/etc \
+    --localstatedir=${MINGW_PREFIX}/var/lib \
+    --build=$OSTYPE \
+    --host=$OSTYPE \
+    --target=$OSTYPE \
+    --release-channel=stable \
+    --enable-ninja \
+    --enable-ccache \
+    --enable-extended \
+    --disable-codegen-tests \
+    --python=${MINGW_PREFIX}/bin/python2 \
+    ${_rust_conf}
 
-[rust]
-debug = false
-codegen-units-std = 1
-debuginfo-level = 0
-channel = ["stable"]
-rpath = false
-codegen-tests = false
-deny-warnings = true
+  DEP_NGHTTP_ROOT=${MINGW_PREFIX} \
+  DEP_OPENSSL_ROOT=${MINGW_PREFIX} \
+  DEP_Z_ROOT=${MINGW_PREFIX} \
+  /home/User/.bin/noti nice -n19 ${MINGW_PREFIX}/bin/python2 ../${_realname}c-${pkgver}-src/x.py build -j7 --verbose
+}
 
-[target.x86_64-pc-windows-gnu]
-llvm-config = ["${MINGW_PREFIX}/bin/llvm-config"]
-END
-
-  /home/User/.go/bin/noti nice -n19 ${MINGW_PREFIX}/bin/python2 ../${_realname}c-${pkgver}-src/x.py build -j7 --verbose
+check() {
+  cd "${srcdir}/${CARCH}"
+  # it might fail on Windows
+  ${MINGW_PREFIX}/bin/python2 ../${_realname}c-${pkgver}-src/x.py test || true
 }
 
 package() {
