autocommit on change

diff --git a/mingw-w64-rust/PKGBUILD-beta b/mingw-w64-rust/PKGBUILD-beta
--- a/mingw-w64-rust/PKGBUILD-beta
+++ b/mingw-w64-rust/PKGBUILD-beta
@@ -20,16 +20,20 @@ makedepends=("bison"
              "${MINGW_PACKAGE_PREFIX}-curl"
              "${MINGW_PACKAGE_PREFIX}-libffi"
              "${MINGW_PACKAGE_PREFIX}-libssh2"
+             "${MINGW_PACKAGE_PREFIX}-lldb"
+             "${MINGW_PACKAGE_PREFIX}-llvm"
              "${MINGW_PACKAGE_PREFIX}-ninja"
              "${MINGW_PACKAGE_PREFIX}-openssl"
-             "${MINGW_PACKAGE_PREFIX}-python2"
+             "${MINGW_PACKAGE_PREFIX}-python3"
              $([[ "$_bootstrapping" == "no" ]] && echo "${MINGW_PACKAGE_PREFIX}-rust")
              "${MINGW_PACKAGE_PREFIX}-zlib")
 options=('staticlibs')
+#install=rust.install
 source=("https://static.rust-lang.org/dist/2020-08-26/rustc-beta-src.tar.xz"
         "force-curl-rust.patch"
         "0001-add-missing-libs.patch"
         "0002-fix-install-msys2.patch"
+        "0003-link-with-system-curl.patch"
         "0004-unbundle-gcc.patch"
         "0005-win32-config.patch"
         "LLVM_TARGETS_TO_BUILD.patch"
@@ -42,8 +46,9 @@ prepare() {
 
   cd ${srcdir}/${_realname}c-${pkgver}-src
   patch -p1 -i "${srcdir}/force-curl-rust.patch"
-  #patch -p1 -i "${srcdir}/0001-add-missing-libs.patch"
+  patch -p1 -i "${srcdir}/0001-add-missing-libs.patch"
   patch -p1 -i "${srcdir}/0002-fix-install-msys2.patch"
+  #patch -p1 -i "${srcdir}/0003-link-with-system-curl.patch"
   patch -p1 -i "${srcdir}/0004-unbundle-gcc.patch"
   patch -p1 -i "${srcdir}/0005-win32-config.patch"
   patch -p1 -i "${srcdir}/LLVM_TARGETS_TO_BUILD.patch"
@@ -60,8 +65,8 @@ build() {
   if [ "${_bootstrapping}" = "no" ]; then
     _rust_conf+=("--local-rust-root=$(cygpath -m ${MINGW_PREFIX})")
   fi
-  
-#  --tools="analysis,cargo,src" \
+
+  export LIBSSH2_SYS_USE_PKG_CONFIG=1
 
   MSYS2_ARG_CONV_EXCL="--prefix;--sysconfdir;--localstatedir" \
   ../${_realname}c-${pkgver}-src/configure \
@@ -71,31 +76,47 @@ build() {
     --build=$OSTYPE \
     --host=$OSTYPE \
     --target=$OSTYPE \
-    --release-channel="beta" \
+    --release-channel=beta \
     --enable-ninja \
     --disable-docs \
+    --disable-compiler-docs \
     --enable-extended \
     --disable-codegen-tests \
-    --enable-locked-deps \
-    --disable-sanitizers \
     --enable-parallel-compiler \
-    --python=${MINGW_PREFIX}/bin/python2 \
-    --llvm-root=${MINGW_PREFIX} \
+    --python=${MINGW_PREFIX}/bin/python3 \
     ${_rust_conf}
+    # i686 builds fails with (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
+    # Probably we have to apply one of Rust's LLVM patches to our LLVM package.
+    # --llvm-root=${MINGW_PREFIX} \
 
-  nice -n19 ${MINGW_PREFIX}/bin/python2 ../${_realname}c-${pkgver}-src/x.py build -j7 --verbose
+  DEP_NGHTTP_ROOT=${MINGW_PREFIX} \
+  DEP_OPENSSL_ROOT=${MINGW_PREFIX} \
+  DEP_Z_ROOT=${MINGW_PREFIX} \
+  ${MINGW_PREFIX}/bin/python3 ../${_realname}c-${pkgver}-src/x.py build -j7 --verbose
+}
+
+check() {
+  cd "${srcdir}/${CARCH}"
+  # it might fail on Windows
+  ${MINGW_PREFIX}/bin/python3 ../${_realname}c-${pkgver}-src/x.py test || true
 }
 
 package() {
   cd "${srcdir}/${CARCH}"
-
-  DESTDIR=${pkgdir} nice -n19 ${MINGW_PREFIX}/bin/python2 ../${_realname}c-${pkgver}-src/x.py install -j7 --verbose
+  DEP_NGHTTP_ROOT=${MINGW_PREFIX} \
+  DEP_OPENSSL_ROOT=${MINGW_PREFIX} \
+  DEP_Z_ROOT=${MINGW_PREFIX} \
+  DESTDIR=${pkgdir} ${MINGW_PREFIX}/bin/python3 ../${_realname}c-${pkgver}-src/x.py install -j7 --verbose
 
   rm -f ${pkgdir}${MINGW_PREFIX}/bin/libgcc*.dll
   rm -f ${pkgdir}${MINGW_PREFIX}/bin/libstd*.dll
   rm -f ${pkgdir}${MINGW_PREFIX}/bin/libwinpthread*.dll
 
+  install -Dm644 ${srcdir}/${_realname}c-${pkgver}-src/LICENSE-APACHE "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}/LICENSE-APACHE"
+  install -Dm644 ${srcdir}/${_realname}c-${pkgver}-src/LICENSE-MIT "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}/LICENSE-MIT"
+
   mkdir -p "${pkgdir}${MINGW_PREFIX}/share/bash-completion/completions/cargo"
   install -d "${pkgdir}${MINGW_PREFIX}/share/bash-completion/completions"
-  mv "${pkgdir}${MINGW_PREFIX}/etc/bash_completion.d/cargo" "${pkgdir}${MINGW_PREFIX}/share/bash-completion/completions/cargo"
+  mv "${pkgdir}${MINGW_PREFIX}/etc/bash_completion.d/cargo" \
+     "${pkgdir}${MINGW_PREFIX}/share/bash-completion/completions/cargo"
 }
