autocommit on change

diff --git a/mingw-w64-clang-9/PKGBUILD - копия b/mingw-w64-clang-9/PKGBUILD - копия
--- a/mingw-w64-clang-9/PKGBUILD - копия
+++ b/mingw-w64-clang-9/PKGBUILD - копия
@@ -25,14 +25,13 @@ pkgname=("${MINGW_PACKAGE_PREFIX}-${_realname}"
          "${MINGW_PACKAGE_PREFIX}-compiler-rt"
          "${MINGW_PACKAGE_PREFIX}-llvm")
 pkgver=9.0.1
-_url=https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1
-pkgrel=1
+_url=https://github.com/llvm/llvm-project/releases/download/llvmorg-${pkgver}
+pkgrel=2
 pkgdesc="C language family frontend for LLVM (mingw-w64)"
 arch=('any')
 url="https://llvm.org/"
 license=("custom:University of Illinois/NCSA Open Source License")
 makedepends=("${MINGW_PACKAGE_PREFIX}-cmake>=3.4.3"
-             "${MINGW_PACKAGE_PREFIX}-z3"
              "${MINGW_PACKAGE_PREFIX}-libffi"
              "${MINGW_PACKAGE_PREFIX}-pkg-config"
              "${MINGW_PACKAGE_PREFIX}-python"
@@ -45,13 +44,14 @@ makedepends=("${MINGW_PACKAGE_PREFIX}-cmake>=3.4.3"
              $([[ "$_generator" == "Ninja" ]] && echo \
                "${MINGW_PACKAGE_PREFIX}-ninja")
              )
-depends=("${MINGW_PACKAGE_PREFIX}-gcc")
+depends=("${MINGW_PACKAGE_PREFIX}-gcc"
+         "${MINGW_PACKAGE_PREFIX}-uasm")
 options=('!debug' 'strip')
-source=(${_url}/llvm-${pkgver}.src.tar.xz{,.sig}
-        ${_url}/clang-${pkgver}.src.tar.xz{,.sig}
-        ${_url}/compiler-rt-${pkgver}.src.tar.xz{,.sig}
-        ${_url}/test-suite-${pkgver}.src.tar.xz{,.sig}
-        ${_url}/clang-tools-extra-${pkgver}.src.tar.xz{,.sig}
+source=(${_url}/llvm-${pkgver}.src.tar.xz
+        ${_url}/clang-${pkgver}.src.tar.xz
+        ${_url}/compiler-rt-${pkgver}.src.tar.xz
+        ${_url}/test-suite-${pkgver}.src.tar.xz
+        ${_url}/clang-tools-extra-${pkgver}.src.tar.xz
         "0001-mingw-w64-use-MSVC-style-ByteAlignment.patch"
         "0002-Fix-GetHostTriple-for-mingw-w64-in-msys.patch"
         "0004-llvm-config-look-for-unversioned-shared-lib-on-win32.patch"
@@ -73,9 +73,6 @@ source=(${_url}/llvm-${pkgver}.src.tar.xz{,.sig}
         "0401-disable-visibility-annotations.patch"
         "0405-fix-conflict-win32-posix-threads.patch"
         "0406-fix-static_asserts-and-unique_ptr-for-libcxx.patch"
-        "0501-fixes-to-get-lldb-building.patch"
-        "0503-lldb-find-mingw-python.patch"
-        "0504-fix-lldb-library-name-mingw.patch"
         "0505-use-gnu-printf.patch"
         "0506-mingw-python-posix-like.patch"
         "0507-declare-exports-for-all-windows-platforms.patch"
@@ -156,15 +153,8 @@ prepare() {
          projects/libcxxabi projects/libunwind projects/openmp projects/test-suite | true
   mv "${srcdir}/clang-${pkgver}.src"               tools/clang
   mv "${srcdir}/clang-tools-extra-${pkgver}.src" tools/clang/tools/extra
-  #mv "${srcdir}/lld-${pkgver}.src"               tools/lld
-  #mv "${srcdir}/lldb-${pkgver}.src"              tools/lldb
-  #mv "${srcdir}/polly-${pkgver}.src"             tools/polly
   mv "${srcdir}/compiler-rt-${pkgver}.src"       projects/compiler-rt
-  #mv "${srcdir}/libcxxabi-${pkgver}.src"         projects/libcxxabi
-  #mv "${srcdir}/libcxx-${pkgver}.src"            projects/libcxx
-  #mv "${srcdir}/libunwind-${pkgver}.src"         projects/libunwind
-  #mv "${srcdir}/openmp-${pkgver}.src"            projects/openmp
-  #mv "${srcdir}/testsuite-${pkgver}.src"         projects/test-suite
+  #mv "${srcdir}/test-suite-${pkgver}.src"         projects/test-suite
 }
 
 build() {
@@ -175,6 +165,13 @@ build() {
 
   local -a extra_config
 
+  if check_option "debug" "y"; then
+    extra_config+=(-DCMAKE_BUILD_TYPE=Debug)
+    VERBOSE="VERBOSE=1"
+  else
+    extra_config+=(-DCMAKE_BUILD_TYPE=Release)
+
+  fi
   # Include location of libffi headers in CPPFLAGS
   FFI_INCLUDE_DIR="$(pkg-config --cflags libffi)"
   FFI_INCLUDE_DIR=$(echo $FFI_INCLUDE_DIR | sed 's|-I||g')
@@ -189,33 +186,62 @@ build() {
     export CXX='clang++'
   fi
 
-#    -DLLVM_OPTIMIZED_TABLEGEN=ON \
-#    -DLLVM_ENABLE_ZLIB=ON \
+
+  
+  export ASM_COMPILER="${MINGW_PREFIX}/bin/uasm.exe"
+  if [ "${CARCH}" == "x86_64" ]; then
+    export ASM_COMPILER_FLAGS=-win64
+  fi
+
+#    -DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=ON \
+#    -DLLVM_ENABLE_CXX1Y=OFF \
+#    -DLLVM_ENABLE_CXX1Z=OFF \
+#    -DCOMPILER_RT_BUILD_SANITIZERS=OFF \
+#    -DLLVM_ENABLE_MODULES=OFF \
+#    -DLLVM_DYLIB_COMPONENTS=all \
+#    CFLAGS=${CFLAGS/-O2/}
+#    CXXFLAGS=${CXXFLAGS/-O2/}
+#    -DLLVM_INCLUDE_TESTS=OFF \
+#    -DLLVM_ENABLE_WERROR=OFF \
+#    -Wwrite-strings -Wc++-compat -Wstrict-prototypes -Wshadow=local -pedantic -D_GNU_SOURCE
+#    -DCOMPILER_RT_BUILD_SANITIZERS=ON \
+#    -DLIBCLANG_BUILD_STATIC=ON \
+#    -DCLANG_LINK_CLANG_DYLIB=OFF \
+#    -DBUILD_SHARED_LIBS=ON \
+#    -DLLVM_COMPILER_IS_GCC_COMPATIBLE=ON \
+#    -DLLVM_USE_SANITIZER=OFF
+#    -DLLVM_BUILD_TOOLS=OFF \
+#    -DLLVM_APPEND_VC_REV=OFF \     -DENABLE_CRASH_OVERRIDES=ON \
+#     -DLLVM_ENABLE_TERMINFO=OFF \
+# -DLLVM_OPTIMIZED_TABLEGEN=ON \
 
   MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
   ${MINGW_PREFIX}/bin/cmake.exe \
     -G"$_generator" \
-    -DCMAKE_BUILD_TYPE=Release \
+    -DCMAKE_VERBOSE_MAKEFILE=OFF \
+    -DENABLE_CRASH_OVERRIDES=ON \
+    -DLLVM_ENABLE_TERMINFO=ON \
     -DLLVM_ENABLE_WERROR=OFF \
     -DLLVM_TARGETS_TO_BUILD="X86" \
-    -DLLVM_ENABLE_Z3_SOLVER=ON \
     -DLLVM_CCACHE_BUILD=OFF \
-    -DLLVM_ENABLE_RTTI=ON \
-    -DCLANG_INCLUDE_DOCS=OFF \
-    -DLLVM_ENABLE_DOXYGEN=OFF \
-    -DLLVM_ENABLE_OCAMLDOC=OFF \
-    -DLLVM_BUILD_EXAMPLES=OFF \
-    -DLLVM_BUILD_DOCS=OFF \
-    -DLLVM_INCLUDE_DOCS=OFF \
-    -DLLVM_INCLUDE_GO_TESTS=OFF \
+    -DCMAKE_ASM_MASM_COMPILER="${ASM_COMPILER}" \
+    -DLIBOMP_ASMFLAGS="${ASM_COMPILER_FLAGS}" \
+    -DLLVM_ENABLE_Z3_SOLVER=OFF \
     -DCMAKE_SYSTEM_IGNORE_PATH=/usr/lib \
     -DFFI_INCLUDE_DIR="${FFI_INCLUDE_DIR}" \
+    -DCMAKE_C_FLAGS="${CFLAGS}" \
+    -DCMAKE_CXX_FLAGS="${CXXFLAGS}" \
     -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
     -DLIBCLANG_BUILD_STATIC=ON \
+    -DLLVM_ENABLE_WARNINGS=OFF \
+    -DCLANG_INCLUDE_DOCS=OFF \
+    -DLLVM_BUILD_DOCS=OFF \
+    -DLLVM_ENABLE_DOXYGEN=OFF \
+    -DLLVM_ENABLE_OCAMLDOC=OFF \
+    -DLLVM_INCLUDE_DOCS=OFF \
     -DLLVM_BUILD_STATIC=OFF \
     -DLLVM_BUILD_LLVM_DYLIB=ON \
     -DLLVM_LINK_LLVM_DYLIB=ON \
-    -DLLVM_ENABLE_ASSERTIONS=OFF \
     -DLLVM_ENABLE_FFI=ON \
     -DLLVM_ENABLE_THREADS=ON \
     -DLLVM_ENABLE_SPHINX=OFF \
@@ -223,11 +249,12 @@ build() {
     "${extra_config[@]}" \
     ../llvm-${pkgver}.src
 
-  # sed away the bad windows style command line parameters (they are translated by msys from /bad to c:\msys\bad
-  #sed -i.orig 's/\/c  \/Fo/-c -Fo/' projects/openmp/runtime/src/CMakeFiles/omp.dir/build.make
-  #sed -i.orig 's/\/safeseh \/coff/-safeseh -coff/' projects/openmp/runtime/src/CMakeFiles/omp.dir/build.make
 
-  /home/User/.go/bin/noti nice -n 19 ${_make_cmd} -j6
+  # sed away the bad windows style command line parameters (they are translated by msys from /bad to c:\msys\bad
+  # sed -i.orig 's/\/c  \/Fo/-c -Fo/' projects/openmp/runtime/src/CMakeFiles/omp.dir/build.make
+  # sed -i.orig 's/\/safeseh \/coff/-safeseh -coff/' projects/openmp/runtime/src/CMakeFiles/omp.dir/build.make
+
+  /home/User/.go/bin/noti.exe nice -n 19 ${_make_cmd} -j7
 
   # Disable automatic installation of components that go into subpackages
   # -i.orig to check what has been removed in-case it starts dropping more than it should
@@ -239,13 +266,18 @@ build() {
   # fix the bad command line parameters, use unix style
 }
 
-
+#check() {
+#  cd "${srcdir}"/build-${CARCH}
+#  # Remove || true once testcase doesn't cause failures.
+#  make check || true
+#  make check-clang || true
+#  make check-polly || true
+#}
 package_clang() {
   pkgdesc="C language family frontend for LLVM (mingw-w64)"
   url="https://clang.llvm.org/"
   depends=("${MINGW_PACKAGE_PREFIX}-llvm=${pkgver}-${pkgrel}"
-           "${MINGW_PACKAGE_PREFIX}-gcc"
-           "${MINGW_PACKAGE_PREFIX}-z3")
+           "${MINGW_PACKAGE_PREFIX}-gcc")
 
   cd "${srcdir}/llvm-${pkgver}.src"
   ${_make_cmd} -C ../build-${CARCH}/tools/clang DESTDIR="${pkgdir}" install
@@ -270,7 +302,6 @@ package_clang-analyzer() {
     -e 's|env python$|&2|' \
     -e 's|/usr/bin/python$|&2|' \
     "${pkgdir}"${MINGW_PREFIX}/bin/scan-view
-
   # Compile Python scripts
   ${MINGW_PREFIX}/bin/python -m compileall "${pkgdir}"${MINGW_PREFIX}/bin/clang-analyzer
   ${MINGW_PREFIX}/bin/python -O -m compileall "${pkgdir}"${MINGW_PREFIX}/lib/clang-analyzer
@@ -296,7 +327,6 @@ package_compiler-rt() {
 package_llvm() {
   pkgdesc="Low Level Virtual Machine (mingw-w64)"
   depends=("${MINGW_PACKAGE_PREFIX}-libffi"
-           "${MINGW_PACKAGE_PREFIX}-z3"
            "${MINGW_PACKAGE_PREFIX}-gcc-libs") # "compiler-rt"
 
   cd "${srcdir}"/llvm-${pkgver}.src
