autocommit on change

diff --git a/mingw-w64-clang/PKGBUILD b/mingw-w64-clang/PKGBUILD
--- a/mingw-w64-clang/PKGBUILD
+++ b/mingw-w64-clang/PKGBUILD
@@ -8,7 +8,7 @@
 # Contributor: Adrian Pop <adrian.pop@liu.se>
 
 
-# We can switch to clang when it fully works with mingw-w64
+# Profiler lib now requires Clang to build
 _compiler=clang
 _generator="MSYS Makefiles"
 #_generator="Ninja"
@@ -31,8 +31,8 @@ pkgname=("${MINGW_PACKAGE_PREFIX}-${_realname}"
          "${MINGW_PACKAGE_PREFIX}-llvm"
          "${MINGW_PACKAGE_PREFIX}-openmp"
          "${MINGW_PACKAGE_PREFIX}-polly")
-pkgver=10.0.1
-pkgrel=15
+pkgver=11.0.0
+pkgrel=1
 pkgdesc="C language family frontend for LLVM (mingw-w64)"
 arch=('any')
 url="https://llvm.org/"
@@ -40,9 +40,6 @@ license=("custom:Apache 2.0 with LLVM Exception")
 makedepends=("${MINGW_PACKAGE_PREFIX}-cmake>=3.4.3"
              "${MINGW_PACKAGE_PREFIX}-z3"
              "${MINGW_PACKAGE_PREFIX}-libffi"
-             "${MINGW_PACKAGE_PREFIX}-compiler-rt"
-             "${MINGW_PACKAGE_PREFIX}-libc++"
-             "${MINGW_PACKAGE_PREFIX}-lld"
              "${MINGW_PACKAGE_PREFIX}-pkg-config"
              "${MINGW_PACKAGE_PREFIX}-python"
              "${MINGW_PACKAGE_PREFIX}-swig"
@@ -56,21 +53,19 @@ makedepends=("${MINGW_PACKAGE_PREFIX}-cmake>=3.4.3"
              )
 depends=("${MINGW_PACKAGE_PREFIX}-gcc")
 options=('!debug' 'strip')
-#_url=https://releases.llvm.org
 _url=https://github.com/llvm/llvm-project/releases/download/llvmorg-${pkgver}
-source=(${_url}/llvm-${pkgver}.src.tar.xz
-        ${_url}/openmp-${pkgver}.src.tar.xz
-        ${_url}/clang-${pkgver}.src.tar.xz
-        ${_url}/compiler-rt-${pkgver}.src.tar.xz
-        ${_url}/test-suite-${pkgver}.src.tar.xz
-        ${_url}/libcxx-${pkgver}.src.tar.xz
-        ${_url}/libcxxabi-${pkgver}.src.tar.xz
-        ${_url}/clang-tools-extra-${pkgver}.src.tar.xz
-        ${_url}/lld-${pkgver}.src.tar.xz
-        ${_url}/lldb-${pkgver}.src.tar.xz
-        ${_url}/libunwind-${pkgver}.src.tar.xz
-        ${_url}/polly-${pkgver}.src.tar.xz
-        "0001-Add-options-to-link-LLVM-with-compiler-rt-and-libunw.patch"
+source=(${_url}/llvm-${pkgver}.src.tar.xz{,.sig}
+        ${_url}/openmp-${pkgver}.src.tar.xz{,.sig}
+        ${_url}/clang-${pkgver}.src.tar.xz{,.sig}
+        ${_url}/compiler-rt-${pkgver}.src.tar.xz{,.sig}
+        ${_url}/test-suite-${pkgver}.src.tar.xz{,.sig}
+        ${_url}/libcxx-${pkgver}.src.tar.xz{,.sig}
+        ${_url}/libcxxabi-${pkgver}.src.tar.xz{,.sig}
+        ${_url}/clang-tools-extra-${pkgver}.src.tar.xz{,.sig}
+        ${_url}/lld-${pkgver}.src.tar.xz{,.sig}
+        ${_url}/lldb-${pkgver}.src.tar.xz{,.sig}
+        ${_url}/libunwind-${pkgver}.src.tar.xz{,.sig}
+        ${_url}/polly-${pkgver}.src.tar.xz{,.sig}
         "0002-Fix-GetHostTriple-for-mingw-w64-in-msys.patch"
         "0004-llvm-config-look-for-unversioned-shared-lib-on-win32.patch"
         "0005-add-pthread-as-system-lib-for-mingw.patch"
@@ -79,26 +74,18 @@ source=(${_url}/llvm-${pkgver}.src.tar.xz
         "0008-enable-emutls-for-mingw.patch"
         "0009-empty-target-prefix-only-msvc.patch"
         "0010-mbig-obj-for-all.patch"
-        "0012-fix-testplugin-linking.patch"
         "0013-Add-Z3-to-system-libraries-list-if-enabled.patch"
-        "0014-Disable-linking-llvm-exegesis-to-dylib.patch"
-        "0015-Avoid-linking-llvm-cfi-verify-to-duplicate-libs.patch"
-        "0016-Add-ffi-to-system-libraries-list-if-enabled.patch"
         "0101-Allow-build-static-clang-library-for-mingw.patch"
         "0102-fix-libclang-name-for-mingw.patch"
         "0104-link-pthread-with-mingw.patch"
         "0105-build-libclang-cpp-fix.patch"
-        "0106-fix-libunwind-extension.patch"
-        "0301-Fix-def-file-exporting-of-symbols-containing-periods.patch"
-        "0502-Add-missing-declarations-for-linking-to-psapi.patch"
-        "0503-lldb-find-mingw-python.patch"
-        "0600-unwind-rename-__personality_routine-to-_Unwind_Personality_Fn.patch"
+        "0106-cmake-Fix-build-of-attribute-plugin-example-on-Windo.patch"
+        "0301-LLD-COFF-Error-out-if-creating-a-DLL-with-too-many-e.patch"
+        "0302-LLD-Allow-configuring-default-ld.lld-backend.patch"
+        "0303-LLD-Ignore-ELF-tests-when-ld.lld-defaults-to-MinGW.patch"
+        "0304-ignore-new-bfd-options.patch"
         "0504-fix-lldb-library-name-mingw.patch"
-        "0801-Don-t-build-LLVMPolly-on-WIN32.patch"
-        "0901-openmp-kpm-lock.patch"
-        "0902-libomp-weak-mingw.patch"
-        "0903-Fix-implib-for-MinGW.patch"
-        "1001-Prevent-linking-to-duplicate-.a-libs-and-dylib.patch")
+        "0801-Don-t-build-LLVMPolly-on-WIN32.patch")
 # Some patch notes :)
 #0001-0099 -> llvm
 #0101-0199 -> clang
@@ -110,32 +97,30 @@ source=(${_url}/llvm-${pkgver}.src.tar.xz
 #0701-0799 -> libc++abi
 #0801-0899 -> polly
 #0901-0999 -> openmp
-#1001-1099
-sha256sums=('c5d8e30b57cbded7128d78e5e8dad811bff97a8d471896812f57fa99ee82cdf3'
+sha256sums=('913f68c898dfb4a03b397c5e11c6a2f39d0f22ed7665c9cefa87a34423a72469'
             'SKIP'
-            'd19f728c8e04fb1e94566c8d76aef50ec926cd2f95ef3bf1e0a5de4909b28b44'
+            '2d704df8ca67b77d6d94ebf79621b0f773d5648963dd19e0f78efef4404b684c'
             'SKIP'
-            'f99afc382b88e622c689b6d96cadfa6241ef55dca90e87fc170352e12ddb2b24'
+            '0f96acace1e8326b39f220ba19e055ba99b0ab21c2475042dbc6a482649c5209'
             'SKIP'
-            'd90dc8e121ca0271f0fd3d639d135bfaa4b6ed41e67bd6eb77808f72629658fa'
+            '374aff82ff573a449f9aabbd330a5d0a441181c535a3599996127378112db234'
             'SKIP'
-            '3418a2d6fd32f4fa2901e740c4a90b512675a941639cdbb9becfbbdc8981f5f1'
+            'add4fc302628b89f238ae95cb594061b57b6482ddf6e92f930718d87fda58619'
             'SKIP'
-            'def674535f22f83131353b3c382ccebfef4ba6a35c488bdb76f10b68b25be86c'
+            '6c1ee6690122f2711a77bc19241834a9219dda5036e1597bfa397f341a9b8b7a'
             'SKIP'
-            'a97ef810b2e9fb70e8f7e317b74e646ed4944f488b02ac5ddd9c99e385381a7b'
+            '58697d4427b7a854ec7529337477eb4fba16407222390ad81a40d125673e4c15'
             'SKIP'
-            'd093782bcfcd0c3f496b67a5c2c997ab4b85816b62a7dd5b27026634ccf5c11a'
+            'fed318f75d560d0e0ae728e2fb8abce71e9d0c60dd120c9baac118522ce76c09'
             'SKIP'
-            '591449e0aa623a6318d5ce2371860401653c48bb540982ccdd933992cb88df7a'
+            'efe7be4a7b7cdc6f3bcf222827c6f837439e6e656d12d6c885d5c8a80ff4fd1c'
             'SKIP'
-            '07abe87c25876aa306e73127330f5f37d270b6b082d50cc679e31b4fc02a3714'
+            '8570c09f57399e21e0eea0dcd66ae0231d47eafc7a04d6fe5c4951b13c4d2c72'
             'SKIP'
-            '741903ec1ebff2253ff19d803629d88dc7612598758b6e48bea2da168de95e27'
+            '8455011c33b14abfe57b2fd9803fb610316b16d4c9818bec552287e2ba68922f'
             'SKIP'
-            'd2fb0bb86b21db1f52402ba231da7c119c35c21dfb843c9496fe901f2d6aa25a'
+            'dcfadb8d11f2ea0743a3f19bab3b43ee1cb855e136bc81c76e2353cd76148440'
             'SKIP'
-            '11aa5f17c8f29e4f2b3e3fa129965179956b332f193eb81f789dc974d3ca6ed1'
             '9b6d3ecb0ef4a38d34aefaefff8c6257ff22d366d84630020d7f079dc8065d97'
             '1f318c0370357fdf9c54ae6d31bad761b0caa58ac099998937b636309ecb6590'
             '7f0c64cd87b61e894be632f180ae5291e1aa9f1d9d382608f659067eeeda7146'
@@ -144,26 +129,18 @@ sha256sums=('c5d8e30b57cbded7128d78e5e8dad811bff97a8d471896812f57fa99ee82cdf3'
             'e1c5f6fa15d6ce9af24dde2b038f0c2fb26a18f2f1200c65405adca6f8d15a6a'
             '33400d16d5f6671a8fd60345c3ae44b9777a7d600061957889d14305eb2ad709'
             '1c9efccd40a0e7834c3aa9d819aa25cfdd2cec389d1bd3e8a89bc9ff670a0129'
-            'c486e1d45f6fb2a24823d776d2b47d6930530d423df73cc635f863265210c294'
             'a2f0e8090a9450abe51e43ba9e9c8ff4b2a4024ba394deea4b8aff547e30fc33'
-            '0cf11cd86c8c57b110c590489b849f0445753ff542a984bfc86bbf3ac1d3c022'
-            'bbddabd4175128328a7358c1161f7900a9fa69937ef6e21cdec3ff05ff7fb9b8'
-            '92e771359fbbeaa301b5c8921340a35309c6cb75f149b259f6b7533d1b2e6253'
-            'b2e5fd29bf666998d495a321690c97fe239bb998abcf0739418ac0ea725fecd6'
+            'ddc43bc16f5edaf5290adabd71ce6a8a593fc3f824d7d99acd247bcce88aaf03'
             '01b029f2a21bd998ce374a90d41d214c891dfbb611dfbd9ca147517cd2c228ea'
             '53646dd01af2862473e9719c5223366486268891ccbff86413943a432a8342e9'
             'a60f7328d84628a56a9f626e4dc26ffd0c35292c79eeba62ac3d4f25aef2fe5c'
-            'ab28a1f6afe2cbd3849da9db12346a3ecdcfa6ca3bd546963c3ac6b874b7b33b'
-            'b0958bfb21d011e60f93f943dc616a362b4fbe2ebd4c38955cdc97389a88b5ab'
-            '6ee9d0bd6abe0a3642bb3078fc285b56f945ba6443a9d305d3f54f1c63f0672a'
-            'd1021748be52cfd447cbfff5f1bfcbb540f7d9e80af7c1bb3f2cc4c0c3a79eab'
-            '12939edc95f503ad03a19355c34a617af645b9731e32b8de7c70054241f1aa96'
+            '0098da33ce4cfea2a6b6943c15e769345f89b84ebea28facff4cc8b92a17bc8f'
+            '0b996f438f7c7bf42c789729dfd588a65d5016386e7032e03e8cd52f1dc8bc73'
+            'c74c313e442a5b8fed7c6372ac8ff8f3598c9e33db1b520f1297949e18042e55'
+            '2e1705274dfc55466cc8977e61d569a685e18ce07895cbec2ccf3b848eafd8ee'
+            '778e0db0a5b0657ab05e2a81d83241347a4a41af2b0f9903422f651fa58e8d40'
             'bed7ae642486a8fd0db5afb0b9afcd8a87605de318ad891bf4c9378a2eb09dc2'
-            'bc394e597f8939b6f6630bd88c990f951738aaadacded2f3be71c658e9608fe7'
-            'db8dc554f7780609ee4eb4bc9e3817d4a9409b622f6471c8db06c92705805ead'
-            'f7958638e73273ea6a8df4a4e8726a0904d049fdaea7e84c33db5dec1af08fa8'
-            'a633c38149772f90cc34f83b144185746b5a47f7d3d10a97cb060c31d140ab7e'
-            'd770cfd931ae07019a888cc1b33a76aaae8347c069679a106a0d7ccca56f86b8')
+            'bc394e597f8939b6f6630bd88c990f951738aaadacded2f3be71c658e9608fe7')
 validpgpkeys=('B6C8F98282B944E3B0D5C2530FC3042E345AD05D'  # Hans Wennborg, Google.
               '474E22316ABF4785A88C6E8EA2C794A986419D8A') # Tom Stellard
 noextract=(clang-${pkgver}.src.tar.xz
@@ -200,7 +177,6 @@ prepare() {
       "0008-enable-emutls-for-mingw.patch" \
       "0009-empty-target-prefix-only-msvc.patch" \
       "0010-mbig-obj-for-all.patch" \
-      "0012-fix-testplugin-linking.patch" \
       "0013-Add-Z3-to-system-libraries-list-if-enabled.patch"
 
   # https://bugs.llvm.org/show_bug.cgi?id=25493
@@ -216,35 +192,23 @@ prepare() {
       "0102-fix-libclang-name-for-mingw.patch" \
       "0104-link-pthread-with-mingw.patch" \
       "0105-build-libclang-cpp-fix.patch" \
-      "0106-fix-libunwind-extension.patch"
+      "0106-cmake-Fix-build-of-attribute-plugin-example-on-Windo.patch"
 
   cd "${srcdir}/lld-${pkgver}.src"
   apply_patch_with_msg \
-      "0301-Fix-def-file-exporting-of-symbols-containing-periods.patch"
+      "0301-LLD-COFF-Error-out-if-creating-a-DLL-with-too-many-e.patch" \
+      "0302-LLD-Allow-configuring-default-ld.lld-backend.patch" \
+      "0303-LLD-Ignore-ELF-tests-when-ld.lld-defaults-to-MinGW.patch" \
+      "0304-ignore-new-bfd-options.patch"
 
   cd "${srcdir}/lldb-${pkgver}.src"
   apply_patch_with_msg \
-      "0502-Add-missing-declarations-for-linking-to-psapi.patch" \
-      "0503-lldb-find-mingw-python.patch" \
       "0504-fix-lldb-library-name-mingw.patch"
-
-  cd "${srcdir}/libunwind-${pkgver}.src"
-  apply_patch_with_msg \
-      "0600-unwind-rename-__personality_routine-to-_Unwind_Personality_Fn.patch" \
 
   cd "${srcdir}/polly-${pkgver}.src"
   # With LLVM_LINK_LLVM_DYLIB=ON it's build before LLVM and fails with undefined references to LLVM functions
   apply_patch_with_msg \
       "0801-Don-t-build-LLVMPolly-on-WIN32.patch"
-
-  cd "${srcdir}/openmp-${pkgver}.src"
-  apply_patch_with_msg \
-      "0901-openmp-kpm-lock.patch" \
-      "0902-libomp-weak-mingw.patch" \
-      "0903-Fix-implib-for-MinGW.patch"
-
-  # At the present, clang must reside inside the LLVM source code tree to build
-  # See https://bugs.llvm.org/show_bug.cgi?id=4840
 
   cd "${srcdir}"
   rm -rf clang clang-tools-extra lld lldb polly compiler-rt libcxx \
@@ -285,7 +249,8 @@ build() {
   # https://github.com/martine/ninja/issues/932
 
   if [ "${_compiler}" == "clang" ]; then
-    export CCACHE_CPP2=yes
+    #export CC='clang -stdlib=libc++'
+    #export CXX='clang++ -stdlib=libc++'
     export CC='clang'
     export CXX='clang++'
   fi
@@ -295,8 +260,8 @@ build() {
     export ASM_COMPILER_FLAGS=-win64
   fi
 
-  export CFLAGS="${CFLAGS} -Wno-unused-variable -Wno-unused-command-line-argument -Wno-unknown-pragmas -Wno-empty-translation-unit -Wno-format-extra-args -Wno-format -Wno-attributes -Wno-unused-function"
-  export CXXFLAGS="${CFLAGS}"
+#  export CFLAGS="${CFLAGS} -Wno-unused-variable -Wno-unused-command-line-argument -Wno-unknown-pragmas -Wno-empty-translation-unit -Wno-format-extra-args -Wno-format -Wno-attributes -Wno-unused-function"
+#  export CXXFLAGS="${CFLAGS}"
 
 #export CCACHE_HARDLINK=true
 #export CCACHE_SLOPPINESS=pch_defines,file_macro,time_macros,include_file_mtime,include_file_ctime,file_stat_matches
@@ -309,17 +274,22 @@ build() {
     -G"$_generator" \
     -DCMAKE_VERBOSE_MAKEFILE=OFF \
     -DLLVM_ENABLE_WERROR=OFF \
-    -DLLVM_CCACHE_BUILD=ON \
+    -DLLVM_CCACHE_BUILD=OFF \
     -DLLVM_TARGETS_TO_BUILD="X86" \
     -DCLANG_ANALYZER_BUILD_Z3=ON \
     -DCMAKE_ASM_MASM_COMPILER="${ASM_COMPILER}" \
     -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
     -DCMAKE_SYSTEM_IGNORE_PATH=/usr/lib \
-    -DFFI_INCLUDE_DIR="${FFI_INCLUDE_DIR}" \
+    -DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
+    -DCOMPILER_RT_BUILD_PROFILE=OFF \
+    -DCOMPILER_RT_BUILD_SANITIZERS=OFF \
+    -DCOMPILER_RT_BUILD_XRAY=OFF \
     -DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON \
+    -DFFI_INCLUDE_DIR="${FFI_INCLUDE_DIR}" \
     -DLIBCLANG_BUILD_STATIC=ON \
     -DLIBOMP_ASMFLAGS="${ASM_COMPILER_FLAGS}" \
     -DLIBOMP_FORTRAN_MODULES=ON \
+    -DLLD_DEFAULT_LD_LLD_IS_MINGW=ON \
     -DLLDB_ENABLE_LIBEDIT=OFF \
     -DLLDB_RELOCATABLE_PYTHON=ON \
     -DLLDB_USE_SYSTEM_SIX=ON \
@@ -327,7 +297,7 @@ build() {
     -DLLVM_BUILD_STATIC=OFF \
     -DLLVM_ENABLE_ASSERTIONS=OFF \
     -DLLVM_ENABLE_FFI=ON \
-    -DLLVM_ENABLE_LLD=ON \
+    -DLLVM_ENABLE_LIBCXX=ON \
     -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt;lld;lldb;openmp;polly" \
     -DLLVM_ENABLE_SPHINX=OFF \
     -DLLVM_ENABLE_THREADS=ON \
@@ -342,7 +312,7 @@ build() {
   sed -i.orig 's/\/c  \/Fo/-c -Fo/' projects/openmp/runtime/src/CMakeFiles/omp.dir/build.make
   sed -i.orig 's/\/safeseh \/coff/-safeseh -coff/' projects/openmp/runtime/src/CMakeFiles/omp.dir/build.make
 
-  nice -n19 ${_make_cmd} -j8
+  nice -n19 ${_make_cmd} -j7
 
   # Disable automatic installation of components that go into subpackages
   # -i.orig to check what has been removed in-case it starts dropping more than it should
@@ -364,12 +334,9 @@ build() {
     -DLIBCXX_ENABLE_EXPERIMENTAL_LIBRARY=ON
     -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON
     -DLIBCXX_HAS_WIN32_THREAD_API=ON
-    -DLIBCXX_USE_COMPILER_RT=ON
     -DLIBCXXABI_ENABLE_NEW_DELETE_DEFINITIONS=OFF
     -DLIBCXXABI_ENABLE_SHARED=OFF
     -DLIBCXXABI_ENABLE_STATIC=ON
-    -DLIBCXXABI_USE_COMPILER_RT=ON
-    -DLIBCXXABI_USE_LLVM_UNWINDER=ON
     -DLIBUNWIND_ENABLE_SHARED=ON
     -DLIBUNWIND_USE_COMPILER_RT=ON
     -DLLVM_ENABLE_LLD=ON
@@ -413,13 +380,14 @@ build() {
   ${_make_cmd} unwind cxxabi cxx
 }
 
-#check() {
-#  cd "${srcdir}"/build-${CARCH}
-#  # Remove || true once testcase doesn't cause failures.
+check() {
+ cd "${srcdir}"/build-${CARCH}
+ # Remove || true once testcase doesn't cause failures.
 #  make check || true
 #  make check-clang || true
 #  make check-polly || true
-#}
+  make check-lld || true
+}
 
 package_clang() {
   pkgdesc="C language family frontend for LLVM (mingw-w64)"
@@ -478,7 +446,7 @@ package_compiler-rt() {
 package_libcxx() {
   pkgdesc="C++ Standard Library (mingw-w64)"
   url="https://libcxx.llvm.org/"
-  depends="${MINGW_PACKAGE_PREFIX}-libunwind"
+  depends="${MINGW_PACKAGE_PREFIX}-gcc-libs"
 
   cd "${srcdir}/libcxx"
   ${_make_cmd} -C ../build-libcxx-shared-${CARCH}/projects/libcxx DESTDIR="${pkgdir}" install
@@ -498,7 +466,7 @@ package_openmp() {
 package_libcxxabi() {
   pkgdesc="C++ Standard Library Support (mingw-w64)"
   url="https://libcxxabi.llvm.org/"
-  depends="${MINGW_PACKAGE_PREFIX}-libunwind"
+  depends="${MINGW_PACKAGE_PREFIX}-gcc-libs"
 
   cd "${srcdir}/libcxxabi"
   ${_make_cmd} -C ../build-libcxx-static-${CARCH}/projects/libcxxabi DESTDIR="${pkgdir}" install
@@ -549,7 +517,7 @@ package_llvm() {
   pkgdesc="Low Level Virtual Machine (mingw-w64)"
   depends=("${MINGW_PACKAGE_PREFIX}-libffi"
            "${MINGW_PACKAGE_PREFIX}-z3"
-           "${MINGW_PACKAGE_PREFIX}-gcc-libs") # "compiler-rt"
+           "${MINGW_PACKAGE_PREFIX}-libc++")
 
   cd "${srcdir}"/llvm-${pkgver}.src
 
