autocommit on change

diff --git a/mingw-w64-clang/PKGBUILDok b/mingw-w64-clang/PKGBUILDok
--- a/mingw-w64-clang/PKGBUILDok
+++ b/mingw-w64-clang/PKGBUILDok
@@ -34,7 +34,7 @@ pkgname=("${MINGW_PACKAGE_PREFIX}-${_realname}"
          "${MINGW_PACKAGE_PREFIX}-openmp"
          "${MINGW_PACKAGE_PREFIX}-polly")
 pkgver=9.0.1
-pkgrel=4
+pkgrel=3
 pkgdesc="C language family frontend for LLVM (mingw-w64)"
 arch=('any')
 url="https://llvm.org/"
@@ -331,13 +331,14 @@ build() {
   ${MINGW_PREFIX}/bin/cmake.exe \
     -G"$_generator" \
     -DLLVM_CCACHE_BUILD=ON \
+    -DCMAKE_VERBOSE_MAKEFILE=OFF \
     -DCMAKE_ASM_MASM_COMPILER="${ASM_COMPILER}" \
     -DLIBOMP_ASMFLAGS="${ASM_COMPILER_FLAGS}" \
     -DLIBOMP_FORTRAN_MODULES=ON \
     -DCMAKE_SYSTEM_IGNORE_PATH=/usr/lib \
     -DFFI_INCLUDE_DIR="${FFI_INCLUDE_DIR}" \
     -DCMAKE_C_FLAGS="${CFLAGS}" \
-    -DCMAKE_CXX_FLAGS="${CXXFLAGS} -std=gnu++17" \
+    -DCMAKE_CXX_FLAGS="${CXXFLAGS} -D_GNU_SOURCE" \
     -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
     -DCLANG_ANALYZER_BUILD_Z3=ON \
     -DLIBCLANG_BUILD_STATIC=ON \
@@ -397,9 +398,8 @@ build() {
   sed -i.orig 's/\/c  \/Fo/-c -Fo/' projects/openmp/runtime/src/CMakeFiles/omp.dir/build.make
   sed -i.orig 's/\/safeseh \/coff/-safeseh -coff/' projects/openmp/runtime/src/CMakeFiles/omp.dir/build.make
 
-  # ${_make_cmd} VERBOSE=99 2>&1 | tee build.log | egrep -i '(warn|error)'
-    ${_make_cmd}
-  
+  ${_make_cmd} VERBOSE=1
+
   # Disable automatic installation of components that go into subpackages
   # -i.orig to check what has been removed in-case it starts dropping more than it should
   #
@@ -409,6 +409,14 @@ build() {
   sed -i.orig '/\(compiler-rt\|libcxxabi\|libcxx\|openmp\|libunwind\)\/cmake_install.cmake/d' projects/cmake_install.cmake
   # fix the bad command line parameters, use unix style
 }
+
+#check() {
+#  cd "${srcdir}"/build-${CARCH}
+#  # Remove || true once testcase doesn't cause failures.
+#  make check || true
+#  make check-clang || true
+#  make check-polly || true
+#}
 
 package_clang() {
   pkgdesc="C language family frontend for LLVM (mingw-w64)"
@@ -424,7 +432,7 @@ package_clang() {
   install -Dm644 ../build-${CARCH}/lib/libclang.a ${pkgdir}${MINGW_PREFIX}/lib/libclang.a
   install -Dm644 ../build-${CARCH}/lib/libclang.a ${pkgdir}${MINGW_PREFIX}/lib/libclang_static.a
 
-  
+#  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_clang-analyzer() {
@@ -446,6 +454,9 @@ package_clang-analyzer() {
   # Compile Python scripts
   ${MINGW_PREFIX}/bin/python -m compileall "${pkgdir}"${MINGW_PREFIX}/bin/clang-analyzer
   ${MINGW_PREFIX}/bin/python -O -m compileall "${pkgdir}"${MINGW_PREFIX}/lib/clang-analyzer
+  install -Dm644 LICENSE.TXT "${pkgdir}"${MINGW_PREFIX}/share/licenses/clang-analyzer/LICENSE
+
+#  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_clang-tools-extra() {
@@ -454,6 +465,8 @@ package_clang-tools-extra() {
 
   cd "${srcdir}/llvm-${pkgver}.src"
   ${_make_cmd} -C ../build-${CARCH}/tools/clang/tools/extra -j1 DESTDIR="${pkgdir}" install
+  
+#  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_compiler-rt() {
@@ -463,6 +476,8 @@ package_compiler-rt() {
 
   cd "${srcdir}"/llvm-${pkgver}.src
   ${_make_cmd} -C ../build-${CARCH}/projects/compiler-rt DESTDIR="${pkgdir}" install
+
+#  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_libcxx() {
@@ -471,6 +486,8 @@ package_libcxx() {
 
   cd "${srcdir}/llvm-${pkgver}.src"
   ${_make_cmd} -C ../build-${CARCH}/projects/libcxx -j1 DESTDIR="${pkgdir}" install
+
+ # rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_openmp() {
@@ -479,6 +496,8 @@ package_openmp() {
 
   cd "${srcdir}/llvm-${pkgver}.src"
   ${_make_cmd} -C ../build-${CARCH}/projects/openmp DESTDIR="${pkgdir}" install
+
+#  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_libcxxabi() {
@@ -489,6 +508,8 @@ package_libcxxabi() {
 
   cd "${srcdir}/llvm-${pkgver}.src"
   ${_make_cmd} -C ../build-${CARCH}/projects/libcxxabi -j1 DESTDIR="${pkgdir}" install
+  
+ # rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_libunwind() {
@@ -497,6 +518,8 @@ package_libunwind() {
 
   cd "${srcdir}/llvm-${pkgver}.src"
   ${_make_cmd} -C ../build-${CARCH}/projects/libunwind -j1 DESTDIR="${pkgdir}" install
+
+ # rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_lld() {
@@ -505,6 +528,8 @@ package_lld() {
 
   cd "${srcdir}/llvm-${pkgver}.src"
   ${_make_cmd} -C ../build-${CARCH}/tools/lld -j1 DESTDIR="${pkgdir}" install
+  
+  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_lldb() {
@@ -524,6 +549,8 @@ package_lldb() {
    local _pyver=$(${MINGW_PREFIX}/bin/python -c "import sys;sys.stdout.write('.'.join(map(str, sys.version_info[:2])))")
   ${MINGW_PREFIX}/bin/python -m compileall "${pkgdir}${MINGW_PREFIX}/lib/python${_pyver}/site-packages/lldb"
   ${MINGW_PREFIX}/bin/python -O -m compileall "${pkgdir}${MINGW_PREFIX}/lib/python${_pyver}/site-packages/lldb"
+
+  #rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_llvm() {
@@ -539,6 +566,8 @@ package_llvm() {
   # TODO: why CMake haven't included it?
   cp ../build-${CARCH}/lib/libLLVM.dll.a "${pkgdir}/${MINGW_PREFIX}/lib/"
 
+  install -Dm644 LICENSE.TXT "${pkgdir}${MINGW_PREFIX}/share/licenses/llvm/LICENSE"
+
   # Install CMake stuff
   install -d "${pkgdir}"${MINGW_PREFIX}/share/llvm/cmake/{modules,platforms}
   install -Dm644 "${srcdir}"/llvm-${pkgver}.src/cmake/modules/*.cmake "${pkgdir}"${MINGW_PREFIX}/share/llvm/cmake/modules/
@@ -549,6 +578,8 @@ package_llvm() {
   # fox cmake files.
   local PREFIX_WIN=$(cygpath -wm ${MINGW_PREFIX})
   sed -e "s|${PREFIX_WIN}|${MINGW_PREFIX}|g" -i ${pkgdir}/${MINGW_PREFIX}/lib/cmake/llvm/LLVMExports.cmake
+
+#  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_polly() {
@@ -564,6 +595,8 @@ package_polly() {
   sed -e "s|${PREFIX_WIN}|${MINGW_PREFIX}/|g" \
     -e "s|${SRC_WIN}/build-${CARCH}/lib|${MINGW_PREFIX}/lib|g" \
     -i "${pkgdir}/${MINGW_PREFIX}/lib/cmake/polly/PollyConfig.cmake"
+
+#  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 # Wrappers
