autocommit on change

diff --git a/mingw-w64-clang/PKGBUILD10 b/mingw-w64-clang/PKGBUILD10
--- a/mingw-w64-clang/PKGBUILD10
+++ b/mingw-w64-clang/PKGBUILD10
@@ -64,7 +64,7 @@ source=(${_url}/llvm-${pkgver}.src.tar.xz{,.sig}
         "0011-different-name-for-static-libraries.patch"
         "0012-fix-testplugin-linking.patch"
         "0013-set-cxx-version.patch"
-        "0014-winpthreads-workaround2.patch"
+        "0014-winpthreads-workaround.patch"
         "0101-Allow-build-static-clang-library-for-mingw.patch"
         "0102-fix-libclang-name-for-mingw.patch"
         "0103-Set-the-x86-arch-name-to-i686-for-mingw-w64.patch"
@@ -113,7 +113,7 @@ prepare() {
       "0010-mbig-obj-for-all.patch" \
       "0012-fix-testplugin-linking.patch" \
       "0013-set-cxx-version.patch" \
-      "0014-winpthreads-workaround2.patch" \
+      "0014-winpthreads-workaround.patch" \
 
   # https://bugs.llvm.org/show_bug.cgi?id=25493
   apply_patch_with_msg \
@@ -155,6 +155,13 @@ build() {
 
   local -a extra_config
 
+  if check_option "debug" "y"; then
+    extra_config+=(-DCMAKE_BUILD_TYPE=Debug)
+    VERBOSE="VERBOSE=1"
+  else
+    extra_config+=(-DCMAKE_BUILD_TYPE=Release)
+  fi
+
   # Include location of libffi headers in CPPFLAGS
   FFI_INCLUDE_DIR="$(pkg-config --cflags libffi)"
   FFI_INCLUDE_DIR=$(echo $FFI_INCLUDE_DIR | sed 's|-I||g')
@@ -168,14 +175,15 @@ build() {
     export CC='clang'
     export CXX='clang++'
   fi
-
-#    -DLLVM_OPTIMIZED_TABLEGEN=ON \
-#    -DLLVM_ENABLE_ZLIB=ON \
+  
+  export ASM_COMPILER="${MINGW_PREFIX}/bin/uasm.exe"
+  if [ "${CARCH}" == "x86_64" ]; then
+    export ASM_COMPILER_FLAGS=-win64
+  fi
 
   MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
   ${MINGW_PREFIX}/bin/cmake.exe \
     -G"$_generator" \
-    -DCMAKE_BUILD_TYPE=Release \
     -DLLVM_ENABLE_WERROR=OFF \
     -DLLVM_TARGETS_TO_BUILD=X86 \
     -DLLVM_ENABLE_Z3_SOLVER=OFF \
@@ -221,6 +229,13 @@ build() {
   # fix the bad command line parameters, use unix style
 }
 
+#check() {
+#  cd "${srcdir}"/build-${CARCH}
+#  # Remove || true once testcase doesn't cause failures.
+#  make check || true
+#  make check-clang || true
+#  make check-polly || true
+#}
 
 package_clang() {
   pkgdesc="C language family frontend for LLVM (mingw-w64)"
