autocommit on change

diff --git a/mingw-w64-clang/PKGBUILD - копия b/mingw-w64-clang/PKGBUILD - копия
--- a/mingw-w64-clang/PKGBUILD - копия
+++ b/mingw-w64-clang/PKGBUILD - копия
@@ -34,7 +34,7 @@ pkgname=("${MINGW_PACKAGE_PREFIX}-${_realname}"
          "${MINGW_PACKAGE_PREFIX}-openmp"
          "${MINGW_PACKAGE_PREFIX}-polly")
 pkgver=9.0.1
-pkgrel=7
+pkgrel=6
 pkgdesc="C language family frontend for LLVM (mingw-w64)"
 arch=('any')
 url="https://llvm.org/"
@@ -190,7 +190,6 @@ prepare() {
       "0901-openmp-kpm-lock.patch" \
       "0902-libomp-weak-mingw.patch"
 
-    
 
 
   # At the present, clang must reside inside the LLVM source code tree to build
@@ -224,7 +223,36 @@ build() {
     extra_config+=(-DCMAKE_BUILD_TYPE=Debug)
     VERBOSE="VERBOSE=1"
   else
-    extra_config+=(-DCMAKE_BUILD_TYPE=Release)
+    extra_config+=(-DCMAKE_BUILD_TYPE=Release \
+                   -DLLVM_BUILD_TESTS=OFF \
+                   -DLLVM_BUILD_BENCHMARKS=OFF \
+                   -DLLVM_INCLUDE_DOCS=OFF \
+                   -DLLVM_ENABLE_DOXYGEN=OFF \
+                   -DLLVM_ENABLE_OCAMLDOC=OFF \
+                   -DLLVM_OPTIMIZED_TABLEGEN=ON \
+                   -DLLVM_ENABLE_BINDINGS=OFF \
+                   -DBUILD_SHARED_LIBS=OFF \
+                   -DCLANG_LINK_CLANG_DYLIB=OFF \
+                   -DLLVM_ENABLE_RTTI=ON \
+                   -DLLVM_TARGETS_TO_BUILD=X86 \
+                   -DLLVM_ENABLE_TERMINFO=OFF \
+                   -DLLVM_ENABLE_WERROR=OFF \
+                   -DCLANG_INCLUDE_DOCS=OFF \
+                   -DCLANG_INCLUDE_TESTS=OFF \
+                   -DCLANG_BUILD_EXAMPLES=OFF \
+                   -DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=ON \
+                   -DLLVM_ENABLE_ZLIB=ON \
+                   -DLLVM_ENABLE_CXX1Y=OFF \
+                   -DLLVM_ENABLE_CXX1Z=OFF
+                   -DLLVM_ENABLE_MODULES=OFF \
+                   -DLLVM_ENABLE_MODULE_DEBUGGING=OFF \
+                   -DLLVM_BUILD_EXAMPLES=OFF \
+                   -DLLVM_ENABLE_SPHINX=OFF \
+                   -DLLVM_INCLUDE_EXAMPLES=OFF \
+                   -DLLVM_INCLUDE_DOCS=OFF \
+                   -DLLVM_INCLUDE_GO_TESTS=OFF \
+                   -DLLVM_INCLUDE_TESTS=OFF \
+                   -DLLVM_DYLIB_COMPONENTS=all)
   fi
   # Include location of libffi headers in CPPFLAGS
   FFI_INCLUDE_DIR="$(pkg-config --cflags libffi)"
@@ -234,10 +262,10 @@ build() {
   # https://github.com/martine/ninja/issues/932
 
   if [ "${_compiler}" == "clang" ]; then
-    #export CC='clang -stdlib=libc++'
-    #export CXX='clang++ -stdlib=libc++'
-    export CC='clang'
-    export CXX='clang++'
+    export CC='clang -stdlib=libc++'
+    export CXX='clang++ -stdlib=libc++'
+    #export CC='clang'
+    #export CXX='clang++'
   fi
 
   
@@ -250,8 +278,7 @@ build() {
   ${MINGW_PREFIX}/bin/cmake.exe \
     -G"$_generator" \
     -DLLVM_CCACHE_BUILD=ON \
-    -DLLVM_TARGETS_TO_BUILD=X86 \
-    -DCMAKE_VERBOSE_MAKEFILE=OFF \
+    -DCMAKE_VERBOSE_MAKEFILE=ON \
     -DCMAKE_ASM_MASM_COMPILER="${ASM_COMPILER}" \
     -DLIBOMP_ASMFLAGS="${ASM_COMPILER_FLAGS}" \
     -DLIBOMP_FORTRAN_MODULES=ON \
@@ -267,7 +294,7 @@ build() {
     -DLIBCXX_HAS_WIN32_THREAD_API=ON \
     -DLIBCXXABI_ENABLE_SHARED=OFF \
     -DLIBUNWIND_ENABLE_SHARED=OFF \
-    -DLLVM_BUILD_STATIC=OFF \
+    -DLLVM_BUILD_STATIC=ON \
     -DLLVM_BUILD_LLVM_DYLIB=ON \
     -DLLVM_LINK_LLVM_DYLIB=ON \
     -DLLVM_ENABLE_ASSERTIONS=OFF \
@@ -299,13 +326,13 @@ build() {
   # fix the bad command line parameters, use unix style
 }
 
-#check() {
-#  cd "${srcdir}"/build-${CARCH}
-#  # Remove || true once testcase doesn't cause failures.
-#  make check || true
-#  make check-clang || true
-#  make check-polly || true
-#}
+check() {
+  cd "${srcdir}"/build-${CARCH}
+  # Remove || true once testcase doesn't cause failures.
+  make check || true
+  make check-clang || true
+  make check-polly || true
+}
 
 package_clang() {
   pkgdesc="C language family frontend for LLVM (mingw-w64)"
@@ -321,6 +348,7 @@ package_clang() {
   install -Dm644 ../build-${CARCH}/lib/libclang.a ${pkgdir}${MINGW_PREFIX}/lib/libclang.a
   install -Dm644 ../build-${CARCH}/lib/libclang.a ${pkgdir}${MINGW_PREFIX}/lib/libclang_static.a
 
+#  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_clang-analyzer() {
@@ -344,6 +372,7 @@ package_clang-analyzer() {
   ${MINGW_PREFIX}/bin/python -O -m compileall "${pkgdir}"${MINGW_PREFIX}/lib/clang-analyzer
   install -Dm644 LICENSE.TXT "${pkgdir}"${MINGW_PREFIX}/share/licenses/clang-analyzer/LICENSE
 
+  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_clang-tools-extra() {
@@ -353,6 +382,7 @@ package_clang-tools-extra() {
   cd "${srcdir}/llvm-${pkgver}.src"
   ${_make_cmd} -C ../build-${CARCH}/tools/clang/tools/extra -j1 DESTDIR="${pkgdir}" install
 
+  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_compiler-rt() {
@@ -363,6 +393,7 @@ package_compiler-rt() {
   cd "${srcdir}"/llvm-${pkgver}.src
   ${_make_cmd} -C ../build-${CARCH}/projects/compiler-rt DESTDIR="${pkgdir}" install
 
+  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_libcxx() {
@@ -372,6 +403,7 @@ package_libcxx() {
   cd "${srcdir}/llvm-${pkgver}.src"
   ${_make_cmd} -C ../build-${CARCH}/projects/libcxx -j1 DESTDIR="${pkgdir}" install
 
+  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_openmp() {
@@ -381,6 +413,7 @@ package_openmp() {
   cd "${srcdir}/llvm-${pkgver}.src"
   ${_make_cmd} -C ../build-${CARCH}/projects/openmp DESTDIR="${pkgdir}" install
 
+  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_libcxxabi() {
@@ -392,6 +425,7 @@ package_libcxxabi() {
   cd "${srcdir}/llvm-${pkgver}.src"
   ${_make_cmd} -C ../build-${CARCH}/projects/libcxxabi -j1 DESTDIR="${pkgdir}" install
 
+  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_libunwind() {
@@ -401,6 +435,7 @@ package_libunwind() {
   cd "${srcdir}/llvm-${pkgver}.src"
   ${_make_cmd} -C ../build-${CARCH}/projects/libunwind -j1 DESTDIR="${pkgdir}" install
 
+  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_lld() {
@@ -410,6 +445,7 @@ package_lld() {
   cd "${srcdir}/llvm-${pkgver}.src"
   ${_make_cmd} -C ../build-${CARCH}/tools/lld -j1 DESTDIR="${pkgdir}" install
 
+  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_lldb() {
@@ -430,7 +466,7 @@ package_lldb() {
   ${MINGW_PREFIX}/bin/python -m compileall "${pkgdir}${MINGW_PREFIX}/lib/python${_pyver}/site-packages/lldb"
   ${MINGW_PREFIX}/bin/python -O -m compileall "${pkgdir}${MINGW_PREFIX}/lib/python${_pyver}/site-packages/lldb"
 
-  install -Dm644 tools/lldb/LICENSE.TXT "${pkgdir}${MINGW_PREFIX}/share/licenses/lldb/LICENSE"
+  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_llvm() {
@@ -459,6 +495,7 @@ package_llvm() {
   local PREFIX_WIN=$(cygpath -wm ${MINGW_PREFIX})
   sed -e "s|${PREFIX_WIN}|${MINGW_PREFIX}|g" -i ${pkgdir}/${MINGW_PREFIX}/lib/cmake/llvm/LLVMExports.cmake
 
+  rm -rf ${pkgdir}${MINGW_PREFIX}/share
 }
 
 package_polly() {
@@ -475,6 +512,7 @@ package_polly() {
     -e "s|${SRC_WIN}/build-${CARCH}/lib|${MINGW_PREFIX}/lib|g" \
     -i "${pkgdir}/${MINGW_PREFIX}/lib/cmake/polly/PollyConfig.cmake"
 
+  rm -rf ${pkgdir}${MINGW_PREFIX}/4e
 }
 
 # Wrappers
